### ISSUE TITLE
[BUG]: mysql piece won't connect  - 'Internal Connection error, failed please check your console.'

### ISSUE THREAD

**Issue by spinnaker1** [activepieces/activepieces#1875]
**Describe the bug**
Using the MySQL piece to connect to a MySQL database, does not work. It returns error in red color font 'Internal Connection error, failed please check your console.'

**To Reproduce**
insert the mysql database connection credentials and click 'save'.

**Expected behavior**
Should connect to a public trusted MySQL Database without errors.

**Additional context**
Using freemysqlhosting.net for testing.

**Comment by abuaboud** [comment]
I couldn't reproduce on the cloud or dev environment.

Can you please tell me more about your setup is it based on postgres or sqlite3?

**Comment by abuaboud** [comment]
Can you also check the backend logs, is there any error?

**Comment by abuaboud** [comment]
Fixed and released 0.7.1

**Comment by spinnaker1** [comment]
> Fixed and released 0.7.1

it still doesn't work for me. Also there is nothing in the container output.

**Comment by abuaboud** [comment]
Hey @spinnaker1, can you check if the side navbar changed to verify the version is 0.7.1? 

Also, could you let me know which piece you're trying to use?

**Comment by spinnaker1** [comment]
> Hey @spinnaker1, can you check if the side navbar 

I dont see any version information. 
![screenshot_0 7 1](https://github.com/activepieces/activepieces/assets/37003472/54ef18a0-c2a1-46a3-aefc-096897acf5e9)
changed to verify the version is 0.7.1?
I dont see any version information in anywhere. 

> Also, could you let me know which piece you're trying to use?
'youtube new video' piece to start the workflow and then 'mysql' piece with 'find rows'.

**Comment by abuaboud** [comment]
@spinnaker1 Can you please check the video, am I doing the right steps to reproduce your issue?

If you have discord, please join the server, I am also happy to chat there to get it fixed as soon as possible.

[Flows - Activepieces.webm](https://github.com/activepieces/activepieces/assets/1812998/75355c49-2e5e-471c-a225-83abb7c5b818)
