### ISSUE TITLE
[BUG]: Multiple small issues when upgrading from 0.68.1 to 0.68.2 or 0.68.3

### ISSUE THREAD

**Issue by itwseood** [activepieces/activepieces#9190]
**Describe the bug**
Self-hosted. After moving from 0.68.1 to 0.68.2 a few different issues appeared:
1. All flows step Generated test data disappeared for all steps;
2. On publishing flow draft, it creates new version, but status remain "Draft";
3. On clicking on a specific flow, that calls a sub-flow with larger "Test Data" set, browser page becomes unresponsive;
4. On attempting to revert back to 0.68.1 via docker compose, the AP shows the flows, but when clicking on project folder with flows or on "All flows", it says "no flows" with triggered server error 500. 

Let me know if I need to break down these into separate issues.

**To Reproduce Flow Step test data missing - after upgrading to 0.68.2 / 0.68.3**
1. Updated via docker compose from version 0.68.1 to 0.68.2. Same tested with 0.68.1 updated to 0.68.3
2. Login and opening a flow;
3. Previously preserved Generate Sample data for each step is now unavailable and needs to be re-generated - this is for all steps of all existing and already tested flows, even published flows;

**Expected behavior**
To have already Generated Test Data for all existing flow steps that are already tested.

**Screenshots**
<img width="1912" height="833" alt="Image" src="https://github.com/user-attachments/assets/5931b2eb-8936-4cd7-a495-3529d52b0806" />

---

**To Reproduce Flow Not Published issue - after upgrading to 0.68.2 / 0.68.3**
1. Updated via docker compose from version 0.68.1 to 0.68.2. Same tested with 0.68.1 updated to 0.68.3
2. Open any flow. 
3. Make changes to the flow, click on Publish.
4. Flow says saved sucessfully, but appears to be in Draft. Every attempt to save after this, generates new versions.
5. Additionally it came to my attention that Last Modified date changes even after just opening the Flow, and not modifying anything in it. Adding this here as it might be related to this particular issue.

**Expected behavior**
To have the flow published status updated, not allowing multiple versions if there are no changes in the published flow.

**Screenshots**
<img width="1823" height="961" alt="Image" src="https://github.com/user-attachments/assets/3595d9a4-b036-44e6-93bb-9b30a142ecf7" />

---

**To Reproduce Page Unresponsive error**
1. Updated via docker compose from version 0.68.1 to 0.68.2. Same tested with 0.68.1 updated to 0.68.3
2. Opened specific flow, that calls a sub-flow. This step had previously field Example Response (For Testing) *, and in the data iw bit larger ~150KB.
3. Page freezes on all browsers tested.

**Expected behavior**
To open the step without freezing as otherwise it can't be tested successfully.

**Screenshots**
Problem:  <img width="1803" height="849" alt="Image" src="https://github.com/user-attachments/assets/3e71e047-46c6-437a-8bcb-efa8fb951082" />
Expected behavior: <img width="477" height="602" alt="Image" src="https://github.com/user-attachments/assets/f1ccc6d1-c455-4ee6-b093-c61a0afa1737" />

---

**To Reproduce AP version change error**
Steps to reproduce the behavior on the update revert:
1. Updated via docker compose from version 0.68.1 to 0.68.2. Same tested with 0.68.1 updated to 0.68.3
2. Detected aforementioned problems;
3. Via docker compose go back to the latest stable version 0.68.1;
4. Open project page;
5. Click on All flows;
6. Instead list of flows it is shown "No flows found" and server error 500 in the browser console, (possible routing problem?)

**Expected behavior**
To have the AP instance working normally and show list with all flows.

**Screenshots**
<img width="1399" height="534" alt="Image" src="https://github.com/user-attachments/assets/62f49146-fe9e-4f3b-b78e-9d6f0c9d340b" />

**Additional context**
I have tested with different browsers, cleared cache, and on two separate servers - the same behavior happens for both the instances. Let me know if any additional information is needed or these needs to be broken down into separate issues each. Hope this helps!

**Comment by abuaboud** [comment]
Hi @itwseood 

I think most of issues is solved in next release (0.69.0), can you expand the response of list flows endpoint

**Comment by itwseood** [comment]
Hi @abuaboud, thank you for your comments! 

I will gladly provide more information. Just to confirm - do you need such for "To Reproduce Page Unresponsive error" I mentioned, or some other?

Best,
Martin

**Comment by itwseood** [comment]
Hi @abuaboud, I have tested v0.69.0, and these errors still appear on it too. I will try to provide a bit more information based on some more tests I have performed, listed the same way as my initial report:

### To Reproduce Flow Step test data missing - after upgrading from 0.68.1 to 0.69.0**
1. Updated via docker compose from version 0.68.1 to 0.69.0.
2. Login and opening existing flow.
3. Click on any step with previously available Generate Sample data;
4. Previously available, now all Sample data for all flows and their steps are gone, no matter whether the flow is old.**4. [NEW]:** On exporting Flows from the 0.69.0 and older version (stable 0.68.1 without these), it seems the new one has a new **sampleDataSettings** object added with keys: _lastTestDate_, _sampleDataFileId_, _sampleDataInputFileId_. 

**Expected behavior**
To preserve the already Generated Sample Data.

**Screenshots**:
Here is the difference in the exported data that hints to me that the sample data is now different in the last versions (might be wrong):
<img width="1580" height="900" alt="Image" src="https://github.com/user-attachments/assets/070af8e2-422d-4419-b259-7f38c4d49815" />

### Question: Is there a structural change in how Generate Sample data is saved, and should we re-test all workflows with new test data? Can we keep the old data we had in place somehow?

-----------

### To Reproduce Flow Not Published issue - after upgrading to 0.68.1 / 0.69.0
This still appears as an error in 0.69.0
1. Updated via docker compose from version 0.68.1 to 0.69.0.
2. Open an old, published flow; 
3. Flow becomes a draft one, triggering the last modified date, even no change is made on it.
4. On Publish, the screen Flicks, there is a message "Flow published", but actually the flow is still in Draft. Providing updated screenshot from 0.69.0

**Screenshots**:
<img width="1801" height="904" alt="Image" src="https://github.com/user-attachments/assets/7d6f5de4-ad61-42e9-a000-0e7e5d45d21c" />

-----------

### To Reproduce Page Unresponsive error

1. Updated via docker compose from version 0.68.1 to 0.69.0.
2. Opened a flow, and in it, a flow step that **calls a sub-flow**.
3. Page freezes on all browsers tested.
4. [NEW] This step has "function enabled" _Example Response (For Testing) *_, and in it, there is nested JSON data with approximate size of ~150KB. 
5. [NEW] When I make a clean import of the same flow with deleted _Example Response (For Testing) *_ data, the step opens without a problem, so I assume there is some kind of new function enabled limitation or a change in the tool and it enters into a loop. 

**Expected behavior**
To open the step without freezing, as otherwise it can't be tested successfully. The test data is larger as it needs to cover several conditions.

**Screenshots:**
v0.69.0 - sub-flow with deleted _Example Response (For Testing) *_ data 
<img width="1630" height="956" alt="Image" src="https://github.com/user-attachments/assets/f952fc53-c6f4-4772-8776-965ac730f938" />

v0.69.0 - with the presented data (identical to 0.68.2 and higher):
<img width="1803" height="849" alt="Image" src="https://github.com/user-attachments/assets/d437c7d0-3348-438d-8449-2c900161c8b7" />

### Question: Is there any newly introduced limit for "function enabled" input fields in a step, or any structural change in the sub_flow module that may trigger such error?

--------

### To Reproduce AP version downgrade error
Steps to reproduce the behavior on the update revert:

1. Updated via docker compose from version 0.68.1 to 0.69.0.
2. Via docker compose go back to 0.68.1;
3. Open project page;
4. Click on All flows;
5. Instead list of flows it is shown "No flows found" and server error 500 in the browser console, (possible routing problem?)
6. [NEW] I was able to get for you the exact error that is triggered:
_The value of '#/properties/data/items/properties/version/properties/trigger' does not match schema definition_

**Screenshot:**
<img width="1661" height="645" alt="Image" src="https://github.com/user-attachments/assets/7c147fa6-ea79-40fc-a2e6-35470f052994" />

**Expected behavior**
To have the AP instance working normally and show a list of all flows, and be able to open these.

### Question: Is there any breaking structural / database change that may cause this after v0.68.1? Does this mean that no reverting to older versions is possible, and we shall only go with new versions even if they have some problems like those above?

---------
Thank you, do not hesitate to let me know if any other info is needed, and I hope this helps!

**Comment by abuaboud** [comment]
1) The sample data is breaking change that will require to re-test the steps in the new version.
2) Please delete the step and add it again, It will upgrade subflow to 0.4.x in that version you no longer need to provide expected response and will call the flow to actual fetch the data.
3) You can't downgrade activepieces instance at this moment, the flow json structure changes with backward compatible, there is a way to upgrade it but not downgrade it.

**Comment by itwseood** [comment]
Thank you for all your help. We'll consider the advice you gave. Last question - is there a solution for "Flow published" but still staying in draft mode? Or will this just be patched in a new version ahead?

**Comment by abuaboud** [comment]
This should be patched in the next version, we will do a release in couple of pr days, let me know if you still face issues by then
